# Generated by Django 5.2.17 on 2026-09-24 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandoms', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional client or slug identifier for characters, merchandise, or articles', max_length=150),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='item_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='item_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('CHARACTER', 'Character Profile'), ('VIDEO', 'Video / Trailer'), ('AUDIO', 'Audio Track'), ('MERCHANDISE', 'Merchandise Item')], db_index=True, default='ARTICLE', max_length=30),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='fandoms.content'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VIEW', 'Viewed Item'), ('BOOKMARK', 'Bookmarked Item'), ('NOTE', 'Updated Bookmark Note'), ('RATING', 'Rated Content'), ('SUBMISSION', 'Submitted Fan Work'), ('CHATBOT', 'Queried FandomBot AI'), ('FILTER', 'Explored Fandom Category'), ('PROFILE', 'Updated Profile Preferences')], db_index=True, default='VIEW', max_length=30)),
                ('target_type', models.CharField(blank=True, default='Content', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=150)),
                ('target_title', models.CharField(max_length=255)),
                ('category_name', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
