# Generated by Django 5.2.17 on 2026-09-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fandoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('event_type', models.CharField(default='Convention', max_length=100)),
                ('city', models.CharField(db_index=True, max_length=150)),
                ('venue_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_month', models.CharField(blank=True, help_text='e.g. AUG, OCT, NOV', max_length=10)),
                ('date_day', models.CharField(blank=True, help_text='e.g. 14-16', max_length=20)),
                ('year', models.CharField(default='2026', max_length=10)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('map_x', models.FloatField(blank=True, default=50.0, help_text='Percentage X on visual stylized radar map')),
                ('map_y', models.FloatField(blank=True, default=50.0, help_text='Percentage Y on visual stylized radar map')),
                ('ticket_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('attendees_info', models.CharField(blank=True, default='50,000+ Expected', max_length=150)),
                ('status', models.CharField(default='Registration Open', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fandoms.category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
    ]
