# Generated by Django 5.2.17 on 2026-09-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fandoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('tag', models.CharField(choices=[('LIMITED_EDITION', 'Limited Edition'), ('PRE_ORDER', 'Pre-Order Soon'), ('COLLECTIBLE', 'Collectible'), ('OFFICIAL_LICENSED', 'Official Licensed')], db_index=True, default='LIMITED_EDITION', max_length=30)),
                ('is_upcoming', models.BooleanField(db_index=True, default=False)),
                ('drop_date', models.DateTimeField(blank=True, null=True)),
                ('drop_date_text', models.CharField(blank=True, help_text='Display text e.g. Oct 15, 2026 • 12:00 PM EST', max_length=150)),
                ('msrp', models.CharField(blank=True, help_text='Display MSRP preview only', max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_items', to='fandoms.category')),
            ],
            options={
                'verbose_name': 'Merchandise Item',
                'verbose_name_plural': 'Merchandise Items',
                'ordering': ['-view_count', '-created_at'],
            },
        ),
    ]
