# Generated by Django 5.2.17 on 2026-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User dashboard customization settings (layout density, visible widgets, default filters).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('MEMBER', 'Registered User'), ('ADMIN', 'Administrator')], db_index=True, default='MEMBER', help_text='Role assigned to the user defining system permissions.', max_length=20),
        ),
    ]
