# Generated by Django 5.2.17 on 2026-09-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fandoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=255)),
                ('answer', models.TextField()),
                ('universe_name', models.CharField(blank=True, help_text='e.g. Anime, Comics, Gaming', max_length=100)),
                ('badge', models.CharField(default='Curated FAQ', help_text='Tagline badge e.g. Anime Lore • Curated', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Keywords or trigger phrases')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_entries', to='fandoms.category')),
            ],
            options={
                'verbose_name': 'Chatbot FAQ',
                'verbose_name_plural': 'Chatbot FAQs',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_queries', to='chatbot.chatbotfaq')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Query Audit',
                'verbose_name_plural': 'Chatbot Query Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
