# Generated by Django 5.2.17 on 2026-09-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Tv', help_text='Icon identifier (e.g. Tv, Gamepad2, Film, Mic2)', max_length=50)),
                ('accent_color', models.CharField(default='#38BDF8', help_text='Hex color code for branding', max_length=20)),
                ('badge_text_color', models.CharField(default='text-black', max_length=20)),
                ('entry_count', models.CharField(blank=True, default='0+ Entries', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('top_pick', models.CharField(blank=True, max_length=255)),
                ('featured_quote', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('alias', models.CharField(blank=True, max_length=150)),
                ('archetype', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('faction', models.CharField(blank=True, max_length=200)),
                ('tagline', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('stats_json', models.JSONField(blank=True, default=list, help_text='Array of attribute dicts')),
                ('details_json', models.JSONField(blank=True, default=dict, help_text='Dict of lore metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='fandoms.category')),
            ],
            options={
                'verbose_name': 'Character Profile',
                'verbose_name_plural': 'Character Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video Trailer'), ('AUDIO', 'Audio Soundtrack'), ('IMAGE', 'Image Set')], db_index=True, default='ARTICLE', max_length=20)),
                ('media_url', models.URLField(blank=True, help_text='Embed or streaming URL', max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('body_text', models.TextField(blank=True, help_text='Rich text / markdown article body')),
                ('synopsis', models.TextField(blank=True, help_text='Short blurb or synopsis')),
                ('artist_or_author', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, help_text='Formatted duration e.g. 02:45', max_length=50)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_year', models.CharField(blank=True, help_text='e.g. 2026 Remaster', max_length=100)),
                ('popularity_score', models.FloatField(db_index=True, default=0.0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='fandoms.category')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
    ]
