# Generated by Django 5.2.17 on 2026-09-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandoms', '0002_charactersubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('stream_type', models.CharField(choices=[('TRAILER', 'Video Trailer'), ('AUDIO', 'Audio Soundtrack')], db_index=True, default='TRAILER', max_length=20)),
                ('universe_label', models.CharField(blank=True, help_text='Display universe/category label e.g. Anime / Gaming', max_length=100)),
                ('accent_color', models.CharField(default='#A3E635', max_length=20)),
                ('media_url', models.URLField(help_text='YouTube link (e.g. https://youtu.be/x4ztgjvfU60) or audio stream URL', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('synopsis', models.TextField(blank=True)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(default='02:45', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=165)),
                ('release_year', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=4.9)),
                ('ratings_count', models.PositiveIntegerField(default=100)),
                ('views_label', models.CharField(default='1.0M views', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_label', models.CharField(default='10.0k', max_length=50)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_media', to='fandoms.category')),
            ],
            options={
                'verbose_name': 'Stream & Discover Media',
                'verbose_name_plural': 'Stream & Discover Media',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
